Repository italia/design-angular-kit, pull requests merged in 2023-02, with the labels that each got.

#197 feat: ability to filter autocomplete data on backend
  projects/design-angular-kit/src/lib/components/form/input/input.component.html
  projects/design-angular-kit/src/lib/components/form/input/input.component.ts
  projects/design-angular-kit/src/lib/interfaces/form.ts
  src/app/form-input/form-input-example/form-input-example.component.html
  src/app/form-input/form-input-example/form-input-example.component.ts
Labels: enhancement

#218 chore(docs): added docs for the notifications component
  package-lock.json
  projects/design-angular-kit/src/lib/components/core/notifications/notifications.component.html
  projects/design-angular-kit/src/lib/components/core/notifications/notifications.component.ts
  projects/design-angular-kit/src/lib/interfaces/core.ts
  projects/design-angular-kit/src/lib/services/notifications/notifications.service.ts
  src/app/app-routing.module.ts
  src/app/notifications/notifications-example-type/notifications-example-type.component.html
  src/app/notifications/notifications-example-type/notifications-example-type.component.spec.ts
  src/app/notifications/notifications-example-type/notifications-example-type.component.ts
  src/app/notifications/notifications-example/notifications-example.component.html
  src/app/notifications/notifications-example/notifications-example.component.spec.ts
  src/app/notifications/notifications-example/notifications-example.component.ts
  src/app/notifications/notifications-examples/notifications-examples.component.spec.ts
  src/app/notifications/notifications-examples/notifications-examples.component.tpl
  src/app/notifications/notifications-examples/notifications-examples.component.ts
  src/app/notifications/notifications-index/notifications-index.component.html
  src/app/notifications/notifications-index/notifications-index.component.spec.ts
  src/app/notifications/notifications-index/notifications-index.component.ts
  src/app/notifications/notifications-routing.module.ts
  src/app/notifications/notifications-setup/notifications-setup.component.html
  src/app/notifications/notifications-setup/notifications-setup.component.spec.ts
  src/app/notifications/notifications-setup/notifications-setup.component.ts
  src/app/notifications/notifications.module.ts
  src/app/shared/api-parameters/api-parameters.component.html
  src/app/shared/api-parameters/api-parameters.component.ts
  src/assets/table-of-content.json
Labels: enhancement, docs

#217 chore(docs): added docs for the select component
  projects/design-angular-kit/src/lib/abstracts/abstract-form-component.ts
  src/app/app-routing.module.ts
  src/app/select/select-disabled-example/select-disabled-example.component.html
  src/app/select/select-disabled-example/select-disabled-example.component.scss
  src/app/select/select-disabled-example/select-disabled-example.component.ts
  src/app/select/select-example/select-example.component.html
  src/app/select/select-example/select-example.component.scss
  src/app/select/select-example/select-example.component.ts
  src/app/select/select-examples/select-examples.component.scss
  src/app/select/select-examples/select-examples.component.tpl
  src/app/select/select-examples/select-examples.component.ts
  src/app/select/select-group-example/select-group-example.component.html
  src/app/select/select-group-example/select-group-example.component.scss
  src/app/select/select-group-example/select-group-example.component.ts
  src/app/select/select-index/select-index.component.html
  src/app/select/select-index/select-index.component.scss
  src/app/select/select-index/select-index.component.ts
  src/app/select/select-routing.module.ts
  src/app/select/select.module.ts
  src/assets/table-of-content.json
Labels: docs
